name: Maven Build & Generate JAR

on:
  push: 
    branches:
      - main

jobs:
  maven-build:
    name: Build with Maven
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests
        working-directory: dummy

      - name: Upload JAR Artifcat
        uses: actions/upload-artifact@v4
        with:
          name: built-jar
          path: dummy/target/*.jar

  generate-versioned-jar:
    name: Generate Versioned JAR
    runs-on: ubuntu-latest
    needs: maven-build
  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
  
      - name: Download JAR Artifact
        uses: actions/download-artifact@v4
        with: 
          name: built-jar
          path: dummy/target/
  
      - name: Extract Version from pom.xml
        id: get_version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        working-directory: dummy
  
      - name: Rename JAR with Version & Timestamp
        run: |
          mkdir -p build
          JAR_NAME=$(ls dummy/target/*.jar 2>/dev/null | head -n 1)
          if [[ -z "$JAR_NAME" ]]; then
            echo "Error: No JAR file found in dummy/target/. Exiting..."
            exit 1
          fi
          NEW_JAR_NAME="pool-route-monitor-${{ env.VERSION }}-$(date +'%Y%m%d%H%M%S').jar"
          mv "$JAR_NAME" "build/$NEW_JAR_NAME"
          echo "FINAL_JAR=build/$NEW_JAR_NAME" >> $GITHUB_ENV
  
      - name: Upload Versioned JAR
        uses: actions/upload-artifact@v4
        with:
          name: versioned-jar
          path: ${{ env.FINAL_JAR }}
          
